# Generated by Django 4.2.10 on 2024-02-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0003_rename_status_statuses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuses',
            new_name='Statuse',
        ),
        migrations.RenameModel(
            old_name='Event_topics',
            new_name='Topic',
        ),
    ]
