# Generated by Django 4.2.10 on 2024-02-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0014_event_abstract_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='event',
        ),
    ]
