# Generated by Django 4.2.10 on 2024-02-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0015_remove_abstract_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
