# Generated by Django 4.2.10 on 2024-02-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0016_alter_event_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abstract.event'),
        ),
    ]
