# Generated by Django 4.2.10 on 2024-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0020_remove_abstract_editors_delete_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='presentation_preference',
        ),
        migrations.AddField(
            model_name='abstract',
            name='presentation_preference',
            field=models.ManyToManyField(to='abstract.presentation_type'),
        ),
    ]
