# Generated by Django 4.2.10 on 2024-02-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('abstract', '0022_abstract_editors_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='assigned_abstracts', to='auth.group'),
        ),
    ]
