# Generated by Django 4.2.10 on 2024-02-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abstract_form',
            new_name='Abstract',
        ),
        migrations.RenameModel(
            old_name='Abstract_status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='abstract_form',
            new_name='abstract',
        ),
    ]
