# Generated by Django 4.2.10 on 2024-02-21 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0005_author_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='abstract',
        ),
        migrations.AddField(
            model_name='abstract',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abstract.author'),
        ),
    ]
