# Generated by Django 4.2.10 on 2024-02-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0006_remove_author_abstract_abstract_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='abstract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abstract.abstract'),
        ),
    ]
