# Generated by Django 4.2.10 on 2024-02-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0009_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='abstract_body',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
