# Generated by Django 4.2.10 on 2024-02-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0010_abstract_date_updated_alter_abstract_abstract_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
