# Generated by Django 4.2.10 on 2024-02-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0011_alter_abstract_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Rejected.', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='abstract',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='author_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='presenter_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Statuse',
        ),
    ]
