# Generated by Django 4.2.10 on 2024-02-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0012_abstract_status_abstract_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=600)),
            ],
        ),
    ]
