# Generated by Django 4.2.10 on 2024-02-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0017_abstract_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='abstract_body',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.RemoveField(
            model_name='abstract',
            name='presentation_preference',
        ),
        migrations.AddField(
            model_name='abstract',
            name='presentation_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abstract.presentation_type'),
        ),
    ]
