# Generated by Django 4.2.10 on 2024-02-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0024_product_placeorder_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='item_amount',
        ),
    ]
